# PixelReader Upgrade

In [14]:
import moby2
import numpy as np

In [83]:
ardata = moby2.scripting.get_array_data({'season':'2017', 'array_name':'AR4'})

In [84]:
array_pos = np.vstack([ardata['array_x'], ardata['array_y']]).T

In [85]:
ardata

{'array_angle': array([  37.5,  172.5,  112.5, ...,   -1. ,  172.5,   37.5]),
 'array_x': array([-15621.207, -17996.207,  28867.414, ...,      0.   , -44121.207,
        -41746.207]),
 'array_y': array([-27056.724, -22943.103,  -4113.621, ...,      0.   , -18829.483,
        -22943.103]),
 'bias_line': array([12, 27, 21, ..., -1,  3, 18]),
 'bias_name': array(['LN_BIAS_08', 'LN_BIAS_00', 'LN_BIAS_01', ..., 'none', 'LN_BIAS_25',
        'LN_BIAS_24'],
       dtype='|S12'),
 'col': array([ 0,  1,  2, ..., 29, 30, 31]),
 'det_type': array(['tes', 'tes', 'tes', ..., 'dark_squid', 'tes', 'tes'],
       dtype='|S11'),
 'det_uid': array([   0,    1,    2, ..., 2045, 2046, 2047]),
 'df_name': array(['tesdatar00c00', 'tesdatar00c01', 'tesdatar00c02', ...,
        'tesdatar63c29', 'tesdatar63c30', 'tesdatar63c31'],
       dtype='|S13'),
 'fcode': array(['f150', 'f150', 'f220', ..., 'f000', 'f150', 'f150'],
       dtype='|S4'),
 'nom_freq': array([ 150.,  150.,  220., ...,    0.,  150.,  150.]),


In [106]:
# generate pixel dict that i often used automatically
pixel_dict = {}
freqs = np.sort(np.unique(ardata['nom_freq']))[1:] 

for det_id in ardata['det_uid']:
    if np.all(array_pos[det_id,:]==[0,0]):
        #print 'Det %s is [0,0], skipping ...' % det_id
        continue
    if (ardata['det_type'][det_id] != 'tes'):
        #print 'Det %s is not tes, skipping ..' % det_id
        continue
    dets = np.where(np.all(array_pos == array_pos[det_id,:],axis=1))[0]
    pol_dict = {
        'f1':  [i for i in dets if ardata['nom_freq'][i]==freqs[0]],
        'f2': [i for i in dets if ardata['nom_freq'][i]==freqs[1]]
    }
    pixel_id = dets[0]
    pixel_dict[str(pixel_id)]=pol_dict

In [107]:
pixel_dict

{'0': {'f1': [0, 32], 'f2': [216, 248]},
 '1': {'f1': [1, 33], 'f2': [473, 505]},
 '10': {'f1': [10, 42], 'f2': [1094, 1126]},
 '1024': {'f1': [1024, 1056], 'f2': [1817, 1849]},
 '1025': {'f1': [1025, 1057], 'f2': [1819, 1851]},
 '1028': {'f1': [1227, 1259], 'f2': [1028, 1060]},
 '1035': {'f1': [1035, 1067], 'f2': [1413, 1445]},
 '1036': {'f1': [1036, 1068], 'f2': [1991, 2023]},
 '1037': {'f1': [1037, 1069], 'f2': [1734, 1766]},
 '1038': {'f1': [1941, 1973], 'f2': [1038, 1070]},
 '1039': {'f1': [1687, 1719], 'f2': [1039, 1071]},
 '1040': {'f1': [1878, 1910], 'f2': [1040, 1072]},
 '1041': {'f1': [1748, 1780], 'f2': [1041, 1073]},
 '1042': {'f1': [1042, 1074], 'f2': [1806, 1838]},
 '1043': {'f1': [1043, 1075], 'f2': [1359, 1391]},
 '1044': {'f1': [1044, 1076], 'f2': [1804, 1836]},
 '1051': {'f1': [1822, 1854], 'f2': [1051, 1083]},
 '1052': {'f1': [1373, 1405], 'f2': [1052, 1084]},
 '1053': {'f1': [1820, 1852], 'f2': [1053, 1085]},
 '1054': {'f1': [1054, 1086], 'f2': [1944, 1976]},
 '1055

In [105]:
freqs

array([ 150.,  220.])

In [100]:
freqs.sort(order=-1)

ValueError: Cannot specify order when the array has no fields.

In [101]:
np.sort(freqs, )

array([   0.,  150.,  220.])

In [102]:
np.sort(np.array([10,5,0]))

array([ 0,  5, 10])